# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20171123_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='RegisterModel',
        ),
    ]
